@istest
public class SL_Test_faultPartnerSoapSforceCom {
    @istest
    static  void SL_Test_faultPartnerSoapSforceCom(){
            // TO DO: implement unit test
            new faultPartnerSoapSforceCom();
            new faultPartnerSoapSforceCom.ApiFault();
            new faultPartnerSoapSforceCom.InvalidSObjectFault();
            new faultPartnerSoapSforceCom.MalformedQueryFault();
            new faultPartnerSoapSforceCom.InvalidIdFault();
            new faultPartnerSoapSforceCom.MalformedSearchFault();
            new faultPartnerSoapSforceCom.InvalidFieldFault();
            new faultPartnerSoapSforceCom.ApiQueryFault();
            new faultPartnerSoapSforceCom.UnexpectedErrorFault();
            new faultPartnerSoapSforceCom.InvalidQueryLocatorFault();
            new faultPartnerSoapSforceCom.LoginFault();
            new faultPartnerSoapSforceCom.InvalidNewPasswordFault();
        }
}