@isTest(seeAllData=true)
public class UpdateCustomFieldsOnTaskTriggerTest
{
    public static TestMethod void Test0_TestInsertWithValue() {

      /*  BMCServiceDesk__Incident__c incidentObj = new BMCServiceDesk__Incident__c();
        incidentObj.BMCServiceDesk__FKClient__c= UserInfo.getUserid();
        incidentObj.Operational_Catalog_Tier_1__c = 'Administrative';
        incidentObj.Operational_Catalog_Tier_2__c = 'Facilities';
        incidentObj.Product_Catalog_Tier_1__c = 'Laptop';
        incidentObj.Product_Catalog_Tier_2__c = 'MacBook Pro';
        insert incidentObj;
        
        BMCServiceDesk__Task__c incTaskObj = new BMCServiceDesk__Task__c(BMCServiceDesk__FKIncident__c = incidentObj.ID);
        insert incTaskObj;
        
        
        BMCServiceDesk__Problem__c problemObj = new BMCServiceDesk__Problem__c(BMCServiceDesk__Problem_Description__c='Test Description', OwnerId=UserInfo.getUserId());
        problemObj.Operational_Catalog_Tier_1__c = 'Administrative';
        problemObj.Operational_Catalog_Tier_2__c = 'Facilities';
        problemObj.Product_Catalog_Tier_1__c = 'Laptop';
        problemObj.Product_Catalog_Tier_2__c = 'MacBook Pro';
        insert problemObj;
        
        BMCServiceDesk__Task__c probTaskObj = new BMCServiceDesk__Task__c(BMCServiceDesk__FKProblem__c= problemObj.ID);
        insert probTaskObj;
        
        BMCServiceDesk__Change_Request__c changeobj = new BMCServiceDesk__Change_Request__c();
        changeobj.Operational_Catalog_Tier_1__c = 'Administrative';
        changeobj.Operational_Catalog_Tier_2__c = 'Facilities';
        changeobj.Product_Catalog_Tier_1__c = 'Laptop';
        changeobj.Product_Catalog_Tier_2__c = 'MacBook Pro';
        insert changeobj ;
        
        BMCServiceDesk__Task__c changeTaskObj = new BMCServiceDesk__Task__c(BMCServiceDesk__FKChange__c = changeobj.ID);
        insert changeTaskObj;*/
    }
}